server:
  port: 8083
spring:
  datasource:
    url: jdbc:mysql://database-network:3306/bank_sacombank
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
security:
  api:
    secret-key: bank-scb-dHAIA5I6ja
    salt: nVuLSZjAYD