server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://10.0.0.200:3306/bank_viettin
    driver-class-name: com.mysql.jdbc.Driver
    username: admin
    password: 12345678
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect