server:
    port: 8080
spring:
    datasource:
        url: jdbc:mysql://10.0.0.200:3306/z_wallet
        driver-class-name: com.mysql.jdbc.Driver
        username: admin
        password: 12345678
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
    redis:
        client-name: zwallet
        host: 10.0.0.200
        port: 6379
    servlet:
        multipart:
            enabled: true
            max-file-size: 200MB
            max-request-size: 215MB
file:
    upload-dir: ./uploads
bank:
    connector:
        msb:
            base-url: http://localhost:8081
            link-method: /msb/link
            un-link-method: /msb/un-link
            pay-method: /msb/pay
            cash-in-method: /msb/cash-in
            cash-out-method: /msb/cash-out
            bank-name: MSB
            secret-key: bank-msb-dHAIA5I6ja
            salt: nVuLSZjAYD
        vtb:
            base-url: http://localhost:8082
            link-method: /viettin/link
            un-link-method: /viettin/un-link
            pay-method: /viettin/pay
            cash-in-method: /viettin/cash-in
            cash-out-method: /viettin/cash-out
            bank-name: Viet Tin Bank
            secret-key: bank-vtb-dHAIA5I6ja
            salt: nVuLSZjAYD
        scb:
            base-url: http://localhost:8083
            link-method: /sacombank/link
            un-link-method: /sacombank/un-link
            pay-method: /sacombank/pay
            cash-in-method: /sacombank/cash-in
            cash-out-method: /sacombank/cash-out
            bank-name: Sacombank
            secret-key: bank-scb-dHAIA5I6ja
            salt: nVuLSZjAYD
wallet:
    base-url: http://localhost:8080
    add-cash-method: /wallet/add-cash
    sub-tract-cash-method: /wallet/subtract-cash
callback:
    service:
        cashin:
            base-url: http://localhost:8080
            callback-method: /wallet-topup/callback
        cashout:
            base-url: http://localhost:8080
            callback-method: /withdraw/callback
        moneytransfer:
            base-url: http://localhost:8080
            callback-method: /p2p-transfer/callback
        mobilecard:
            base-url: http://localhost:8080
            callback-method: /mobile-card/callback