server:
    port: 8080
spring:
    datasource:
        url: jdbc:mysql://10.0.0.200:3306/z_wallet
        driver-class-name: com.mysql.jdbc.Driver
        username: admin
        password: 12345678
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
    redis:
        client-name: zwallet
        host: 10.0.0.200
        port: 6379
bank:
    connector:
        msb:
            base-url: http://localhost:8081
            link-method: /msb/link
            un-link-method: msb/un-link
            pay-method: /msb/pay
            cash-in-method: /msb/cash-in
            cash-out-method: /msb/cash-out
            bank-name: MSB
wallet:
    base-url: http://localhost:8080
    add-cash-method: /wallet/add-cash
    sub-tract-cash-method: /wallet/subtract-cash