server:
    port: 8080
spring:
    datasource:
        url: jdbc:mysql://database-network:3306/z_wallet
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: admin
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
    redis:
        client-name: zwallet
        host: cache-network
        port: 6379
bank:
    connector:
        msb:
            base-url: http://msb-bank-network:8081
            link-method: /msb/link
            un-link-method: msb/un-link
            pay-method: /msb/pay
            cash-in-method: /msb/cash-in
            cash-out-method: /msb/cash-out
            bank-name: MSB
wallet:
    base-url: http://z-wallet-network:8080
    add-cash-method: /wallet/add-cash
    sub-tract-cash-method: /wallet/subtract-cash
callback:
    service:
        cashin:
            base-url: http://z-wallet-network:8080
            callback-method: /wallet-topup/callback
        cashout:
            base-url: http://z-wallet-network:8080
            callback-method: /withdraw/callback
        moneytransfer:
            base-url: http://z-wallet-network:8080
            callback-method: /p2p-transfer/callback
        mobilecard:
            base-url: http://z-wallet-network:8080
            callback-method: /mobile-card/callback