version: '3.5'
services:
    zwallet:
        container_name: zwallet-api
        build: 
            context: ./z-wallet/
            dockerfile: Dockerfile
        ports: 
            - "8080:8080"
        restart: always
        depends_on:
            - msbbank
            - database
            - cache
        networks:
            wallet-network:
                aliases:
                  - z-wallet-network
    msbbank:
        container_name: bank-msb-api
        build: 
            context: ./bank-msb/
            dockerfile: Dockerfile
        ports: 
            - "8081:8081"
        restart: always
        depends_on:
            - database
        networks:
            wallet-network:
                aliases:
                  - msb-bank-network
    viettinbank:
        container_name: bank-viettin-api
        build: 
            context: ./bank-viettin/
            dockerfile: Dockerfile
        ports: 
            - "8082:8082"
        restart: always
        depends_on:
            - database
        networks:
            wallet-network:
                aliases:
                  - viettin-bank-network
    sacombank:
        container_name: bank-sacom-api
        build: 
            context: ./bank-sacombank/
            dockerfile: Dockerfile
        ports: 
            - "8083:8083"
        restart: always
        depends_on:
            - database
        networks:
            wallet-network:
                aliases:
                  - sacom-bank-network
    database:
        container_name: zwallet-database
        image: mysql
        restart: always
        ports: 
            - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: admin
        volumes:
            - ./db/:/docker-entrypoint-initdb.d
        networks:
            wallet-network:
                aliases:
                  - database-network
    cache:
        container_name: zwallet-cache
        image: redis
        restart: always
        networks:
            wallet-network:
                aliases:
                  - cache-network
networks:
  wallet-network: