version: '3.5'
services:
  cps-withdraw-client:
    container_name: cps-withdraw-client
    build: 
      context: ./withdraw-client/
      dockerfile: Dockerfile
    ports: 
      - "9833:9833"
    environment:
      - PROFILE=qc
      - XMX=256m
    networks:
      - cps-network
  cps-core:
    container_name: cps-core
    build:
      context: ./cps-core/
      dockerfile: Dockerfile
    ports: 
      - "9861:9861"
    environment:
      - PROFILE=qc
      - XMX=256m
    networks:
        cps-network:
          aliases:
            - cps-core-network
  cps-withdraw-provider:
    container_name: cps-withdraw-provider
    build:
      context: ./withdraw-provider/
      dockerfile: Dockerfile
    ports: 
      - "9835:9835"
    environment:
      - PROFILE=qc
      - XMX=256m
    networks:
        cps-network:
          aliases:
            - cps-withdraw-provoder-network
  cps-wallet-topup-client:
    container_name: cps-wallet-topup-client
    build: 
      context: ./wallet-topup-client/
      dockerfile: Dockerfile
    ports: 
      - "9665:9665"
    environment:
      - PROFILE=qc
      - XMX=256m
    networks:
      - cps-network
  cps-wallet-topup-provider:
    container_name: cps-wallet-topup-provider
    build: 
      context: ./wallet-topup-provider/
      dockerfile: Dockerfile
    ports: 
      - "9667:9667"
    environment:
      - PROFILE=qc
      - XMX=256m
    networks:
      cps-network:
          aliases:
            - cps-wallet-topup-provider-network
  cps-simulator:
    container_name: cps-simulator
    build: 
      context: ./simulator/
      dockerfile: Dockerfile
    ports: 
      - "8083:8083"
    environment:
      - PROFILE=qc
      - XMX=256m
    networks:
      cps-network:
          aliases:
            - cps-simulator-network
  cps-withdraw-client-activemq:
    container_name: cps-withdraw-client-activemq
    image: rmohr/activemq
    networks:
      cps-network:
        aliases:
          - cps-withdraw-activemq-network
  cps-core-activemq:
    container_name: cps-core-activemq
    image: rmohr/activemq
    networks:
      cps-network:
        aliases:
          - cps-core-activemq-network
  cps-withdraw-provider-activemq:
    container_name: cps-withdraw-provider-activemq
    image: rmohr/activemq
    networks:
      cps-network:
        aliases:
          - cps-withdraw-provider-activemq-network
  cps-wallet-topup-client-activemq:
    container_name: cps-wallet-topup-client-activemq
    image: rmohr/activemq
    networks:
      cps-network:
        aliases:
          - wallet-topup-client-activemq-network
  cps-wallet-topup-provider-activemq:
    container_name: cps-wallet-topup-provider-activemq
    image: rmohr/activemq
    networks:
      cps-network:
        aliases:
          - wallet-topup-provider-activemq-network
  cps-simulator-activemq:
    container_name: cps-simulator-activemq-activemq
    image: rmohr/activemq
    networks:
      cps-network:
        aliases:
          - cps-simulator-activemq-network
networks:
  cps-network:


